linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - revive
    - misspell

linters-settings:
  revive:
    rules:
      - name: package-comments
        severity: warning
      - name: exported
        severity: warning

issues:
  exclude-use-default: false
