version: "2"
linters:
  enable:
    - misspell
    - revive
  settings:
    revive:
      rules:
        - name: package-comments
          severity: warning
        - name: exported
          severity: warning
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
